### ISSUE TITLE
Redundant if statement

### ISSUE THREAD

**Issue by chumaumenze** [adekoder/flask-validator#8]
https://github.com/adekoder/flask-validator/blob/15f48a96f73d016cbd4a401e67c86bdf9a2fa276/flask_validator/validators.py#L6-L8

I was wondering why we have these nested ifs. @adekoder Is there any reason for this?

**Comment by adekoder** [comment]
Thanks for pointing this out @chumaumenze, i can't remember what i was think at the point of writing that code ,  You can send in a PR to Fix it. Thanks.

**Comment by chumaumenze** [comment]
I am working on one. 

BTW, this is a nice work you have done here.

**Comment by adekoder** [comment]
Ok great.
